### ISSUE TITLE
Unable to find Lingpipe Jar: lingpipe-4.1.0.jar in CLASSPATH

### ISSUE THREAD

**Issue by ChanningPing** [jakelever/knowledgediscovery#1]
When I was trying to install dependency lingpipe with "bash install.lingpipe.sh", it generated the following message "Unable to find Lingpipe Jar: lingpipe-4.1.0.jar in CLASSPATH". Should I manually download the lingpipe-4.1.0.jar? What should I do after downloading the jar? Thank you!

**Comment by jakelever** [comment]
Hi, I've fixed the Lingpipe dependency (a14f8cd8dd8d3a38cb58856a603b5343ae22f259) so it now longer needs to be in the classpath. The install.lingpipe.sh script now downloads the JAR to the dependencies directory and the associated Lingpipe scripts (compile.sh & run.sh) now reference that JAR file directly, so you don't need to update your CLASSPATH at all. Hope that works. I'm just going to do a small run to see what happens.

**Comment by jakelever** [comment]
Closing this
